[project]
name = "ido_event"
authors = [
    { name = "I Do Holding", email = "mustafakhaled.dev@gmail.com"}
]
description = "IDO Event — full event management DocTypes, fixtures, and API"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe==16.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
